artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: url = https://drive.google.com/file/d/1Aws-EZ0m86d9LV8Jc2Pqe3YxuYPn68SN/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion